### ISSUE TITLE
"lgetchar/wrapper.tl:25:14: syntax error: this syntax is no longer valid"

### ISSUE THREAD

**Issue by magnusviri** [3uclidian/lgetchar#2]
> tl --version
	0.13.2
	> make
	tl build
	========================================
	1 syntax error:
	./lgetchar/raw.d.tl:2:13: syntax error: this syntax is no longer valid; use 'local record raw'
	========================================
	1 syntax error:
	./lgetchar/wrapper.tl:25:14: syntax error: this syntax is no longer valid; use 'local record Node'
	========================================
	7 errors:
	lgetchar/init.tl:6:17: cannot index something that is not a record: boolean
	lgetchar/init.tl:10:25: cannot index something that is not a record: boolean
	lgetchar/init.tl:14:25: cannot index something that is not a record: boolean
	lgetchar/init.tl:18:25: cannot index something that is not a record: boolean
	lgetchar/init.tl:23:25: cannot index something that is not a record: boolean
	lgetchar/init.tl:28:9: cannot index something that is not a record: boolean
	lgetchar/init.tl:33:17: cannot index object of type {{number}} with number
	========================================
	1 syntax error:
	lgetchar/wrapper.tl:25:14: syntax error: this syntax is no longer valid; use 'local record Node'
	make: *** [default] Error 1

**Comment by euclidianAce** [comment]
Should be fixed now, thanks!
